plugins:
  - jekyll-remote-theme

remote_theme: yaoyao-liu/minimal-light

# Basic Information 
title: Lobster Logic Solutions
position: Software Consulting
affiliation: "Contact us at:"
email: lobsterlogicsolutions (at) gmail.com

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: lobster logic solutions software development consulting consultancy
description: Lobster Logic Solutions is a software consulting group focusing on Maine businesses.
canonical: https://lobsterlogicsolutions.github.com

# Links 
# If you don't need one of them, you may delete the corresponding line.
github_link: https://github.com/lobsterlogicsolutions

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/img/avatar.png
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon.png

# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: true

# Font
# You can use this option to choose between Serif or Sans Serif fonts.
font: "Serif" # or "Sans Serif"